[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "my_benchmark"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
